#! /bin/bash 

####################################################################################################
#                                                                                                  #  
#    Helper Script to be run inside the tmux session. Allows users to disable select panes by      #  
#    invoking the command mode (C-b : or <prefix> :) and typing the command. For example:          #  
#                                                                                                  #  
#        run-shell './disable-panes 0 1 2' to disable pane 0, pane 1, and pane 2                   #  
#                                                                                                  #  
#        author: Changwoo Yu        last modified: 2024-07-02                                      #
#                                                                                                  #  
####################################################################################################

session='sshs_session'
total_panes=$(tmux list-panes -t $session | wc -l)

mode=$1
shift
panes=$@

read -a raw <<< $panes 
panes=()

for i in ${raw[@]}; do
	panes+=($((i)))	
done 

for i in ${panes[@]}; do
	if [[ $i -ge $total_panes ]]; then 
		continue 
	fi
	tmux select-pane -t $session:0.$i $mode
done 

